# Generated by Django 5.0 on 2024-04-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('headline', models.TextField()),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('profileimg2', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images2')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('clubmanager', models.TextField()),
                ('clubvicemanager', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('phonenumber2', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('category', models.TextField(blank=True)),
                ('clubvision', models.CharField(blank=True, max_length=1000)),
                ('clubdescription', models.CharField(blank=True, max_length=1000)),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
