# Generated by Django 5.0 on 2024-04-16 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='clubmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_as_clubmanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='clubname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_as_clubname', to=settings.AUTH_USER_MODEL),
        ),
    ]
