# Generated by Django 5.0 on 2024-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_clubprofile_clubmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='clubmanager',
            field=models.TextField(),
        ),
    ]
