# Generated by Django 5.0 on 2024-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_clubprofile_clubmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubprofile',
            old_name='phonenumber',
            new_name='phonenumber1',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='clubdescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='clubmanager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='clubvicemanager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='clubvision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='headline',
            field=models.CharField(max_length=300),
        ),
    ]
