# Generated by Django 5.0 on 2024-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_groupuser_user_groupuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ADMIN',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='MANAGER',
            field=models.BooleanField(default=False, verbose_name='Is Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='STUDENT',
            field=models.BooleanField(default=False, verbose_name='Is Student'),
        ),
    ]
